model:
  dac_bert:
    input_size: 16
    vocab_size: 1024
    bert_config: 
      vocab_size: 30522
      hidden_size: 768
      num_hidden_layers: 12
      num_attention_heads: 12
      intermediate_size: 3072
      hidden_act: "gelu"
      hidden_dropout_prob: 0.1
      attention_probs_dropout_prob:  0.1
      max_position_embeddings: 2048
      initializer_range: 0.02
      layer_norm_eps: 1e-12
      pad_token_id: 0
    n_heads: 2
  dac_path: /work/ge43/e43001/runs/baseline_50Hz_librispeech/best/dac/weights.pth

data:
  train:
    roots:
    - "/work/ge43/e43001/datasets/LibriSpeech/train-clean-100"
    - "/work/ge43/e43001/datasets/LibriSpeech/train-clean-360"
    - "/work/ge43/e43001/datasets/LibriSpeech/train-other-500"
    patterns:
    - "**/*.flac"
    - "**/*.flac"
    - "**/*.flac"
    batch_size: 8
    num_workers: 4
  sample_rate: 24000
  val:
    roots:
    - "/work/ge43/e43001/datasets/LibriSpeech/dev-clean"
    - "/work/ge43/e43001/datasets/LibriSpeech/dev-other"
    patterns:
    - "**/*.flac"
    batch_size: 8
    num_workers: 0

train:
  trainer:
    _target_: lightning.Trainer
    accelerator: "gpu"
    devices: -1
    strategy: "ddp"
    precision: bf16-mixed
    check_val_every_n_epoch: 10
    max_epochs: 3300
    limit_val_batches: 40
    gradient_clip_val: 1.0
  ckpt_path:


